# Generated by Django 4.0.3 on 2022-03-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1000)),
                ('link', models.CharField(blank=True, max_length=1000)),
                ('heading', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
                ('summary', models.CharField(max_length=1000)),
                ('highlights', models.CharField(max_length=1000)),
                ('ministry', models.CharField(choices=[('CENTRAL MINISTRY', 'Ministry 1'), ('STATE MINISTRY', 'Ministry 2')], max_length=256)),
            ],
        ),
    ]
