# Generated by Django 4.0.3 on 2022-03-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='assets',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
